apiVersion: v1
kind: Service
metadata:
  name: p2p-share-service
  labels:
    app: p2p-share
spec:
  type: LoadBalancer # Automatically provisions an AWS Elastic Load Balancer (ELB)
  ports:
  - port: 80         # Port exposed publicly
    targetPort: 8080 # Port our Go server runs on inside the container
    protocol: TCP
  selector:
    app: p2p-share   # Directs traffic to pods labeled 'app: p2p-share'
